name: awesome-lint github action

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: awesome-lint (double link)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Scrum/awesome-readme-lint-double-link-action@v0.1.13
        with:
          entry: 'readme.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
